project:
  type: website

website:
  title: "Juan Quinonez"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/juansqw
      - icon: linkedin
        href: https://linkedin.com/juansqw
format:
  html:
    theme: Spacelab
    css: styles.css

editor: visual

