project:
  type: website
  output-dir: docs

website:
  title: "Juan Quinonez"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/juansqw
      - icon: linkedin
        href: www.linkedin.com/in/juan-quinonez
format:
  html:
    theme: Spacelab
    css: styles.css

editor: visual

