---
title: "The Psycology of Money - Book review"
author: "Juan Quinonez"
date: "2022-08-19"
categories: [books, reviews, money]
draft: false
---

I recently finished reading Morgan Housel "The Psychology of Money" and here I share my thoughts and impressions of this book.

I liked this book because it showed that what we think of money is not as black and white as we think. We tend to judge people that go bankrupt right after receiving a huge amount of money (from inheritance or winning the lottery), and people that spend most of their life saving money and living precariously. Housel explain each behavior as the result of what each individual experienced in their lives.

This post will summarize this reading and will highlight some of the concepts that got my attention.

### Chapter 1 - Behavior based by experiences

-   Saving and consumption decisions depend on what unique experiences an individual experienced in their lives (specially in their early youth).

### Chapter 2 - Luck and risk

-   This chapter explained that people's success (or misfortune) is a matter of luck. Bill Gates was lucky enough to study at (this) school that had access to a computer so that he (along with some friends) could set the foundations of Microsoft.

-   Don't act on other people's success (or misfortune), rather study patterns.

### Chapter 3 - Never enough

-   Learn when enough is enough.

-   It's hard to reach a goal when the goal post is moving every day.

### Chapter 4 - Confounding compounding

-   Planet Earth was covered by ice several times. "The big take away from ice age is that you don't need tremendous force to create tremendous results".

### Chapter 5 - Getting wealthy vs staying wealthy

-   There are a million books ways to get wealthy, but the only way to stay wealthy: some combination of frugality and paranoia.

-   If I had to summarize money success in one word it would be "survival"

-   Getting money requires taking risks, being optimistic, and putting yourself out there.

-   But keeping money requires the opposite of taking risk.

    -   It requires humility, and fear that what you've made can be taken away just from you just as fast.
