---
title: "The Importance of a Credit Score"
author: 
  - name: César Díaz Tavera
    email: cesartavera97@gmail.com
  - name: Juan Quiñonez Wu
    email: juansqw@gmail.com
date: "2022-09-07"
bibliography: bibliografia.bib
categories: [credit score, banking, money]
draft: false
citation:
  url: https://juansqw.github.io/jquinonez/posts/series-cs/importance/
params:
  slug: key-concepts-credit-score
  date: 2022-09-07
---

Some businesses can choose who to offer their services to. Such is the case of commercial banks, insurance companies, real estate, among others. With increased competition in different sectors and marketing efforts to attract new customers, companies are faced with a pool of potential customers from which they must select profitable customers, with the highest probability of meeting their payments.

However, companies do not always have complete information about customers, so they cannot perfectly discriminate between good customers and bad customers. This puts companies on the downside of adverse selection in this type of business.

Credit scores opportunistically seek to correct the [adverse selection problems](https://cesardt97.github.io/Blog/posts/series-sc/intro-to-the-study-serie/09-05-2022_intro_study_serie.html) of these entities by summarizing a set of customer characteristics into a score. The central idea of these scales is to score customers according to a set of characteristics and to identify those attributes inherent in good and bad customers. @Bessis2015 defines credit ratings as assessments of the credit standing of borrowers and are excellent tools that best discriminate between defaulters and non-defaulters. The use of credit scores offers an objective way to assess risk, and it is also a consistent approach [@Siddiqi2006] that can be applied to a great number of potential customers in a relative simple procedure (thanks to the technological advances in recent years).

On the other hand, clients seek to improve their scores by making various modifications to their financial behavior (paying debts in arrears, or improving their use of revolving credit, among others), so that companies will offer their services to them.

Once selected, clients can negotiate additional services or lower prices, given their score level, i.e. clients of a commercial bank with a better credit score can receive preferential lending rates.

|   Score   | Number of Good Clients | Cumulative Number of Good Clients | Number of Bad Clients | Cumulative Number of Bad Clients |
|:---------:|:----------------------:|:---------------------------------:|:---------------------:|:--------------------------------:|
| 175 - 200 |          115           |                115                |          10           |                10                |
| 150 - 174 |          105           |                220                |          20           |                30                |
| 125 - 149 |           95           |                315                |          30           |                60                |
| 100 - 124 |           85           |                400                |          40           |               100                |
|  75 - 99  |           75           |                475                |          50           |               150                |
|  50 - 74  |           65           |                540                |          60           |               210                |
|  0 - 49   |           55           |                595                |          70           |               280                |

: Credit Score {#tbl-sc}

Author's elaboration

@tbl-sc shows an example of a credit score and the cumulative number of good and bad clients. Using this information businesses may choose to serve only clients with credit scores above 125. This would mean that they will serve 375 clients, 315 will be good clients and 60 will be bad clients, which implies that, given the cut-off score, 16% of the clients may be bad clients. Low cut-off score will increase the potential clients, but will also increase the chance of getting bad clients.

This table also shows that for every score, there are good and also bad clients, which leads to interpret credit scores as a relative risk metric, indicating the likelihood of a consumer that will not be able to honor its obligations in the short-term. Hence, this score is related to the [probability of default](https://cesardt97.github.io/Blog/posts/series-sc/intro-to-the-study-serie/09-05-2022_intro_study_serie.html), usually, the greater the score, the lower the probability of default.

As a business standard, businesses set a score range in which expert analysis is needed to make a decision. Credit ratings, in sum, are a mix of qualitative and quantitative criteria used to assess the potential clients, but should also expert analysis at the end of the decision process.

Credit scores help asses client creditworthiness, and also allows clients to access better pricing for services. As mentioned above, this metrics summarizes the characteristics of a potential customer, but it does not take into account the macroeconomic context. This means that it is possible that one can find a great customer, with excellent credit score, but cannot honor his debts due to an economic crisis that caused him to loose his job. This limitations should be taken into consideration for further research.

How are credit scores calibrated?

Which characteristics influence in this scale?

These, and more questions are soon to be answered in latter posts.
